// Generated by g.f.com/flora/tools/makego
// DO NOT EDIT!!
package table

type ITable interface {
	Load(filename string) error
}

type ExcelTable struct {
	Tables map[string]ITable
	
	*BoxTableTable
	
	*BroadcastTableTable
	
}

func (tab *ExcelTable) Init() {
	tab.Tables = make(map[string]ITable)
	
	tab.BoxTableTable = NewBoxTableTable()
    tab.Tables["Boxtable.json"] = tab.BoxTableTable
	
	tab.BroadcastTableTable = NewBroadcastTableTable()
    tab.Tables["Broadcasttable.json"] = tab.BroadcastTableTable
	
}
