// Generated by g.f.com/flora/tools/makego
// DO NOT EDIT!!
package table

type ITable interface {
	Load(filename string) error
}

type ExcelTable struct {
	Tables map[string]ITable
	{{range .Structs}}
	*{{.Data 1}}
	{{end}}
}

func (tab *ExcelTable) Init() {
	tab.Tables = make(map[string]ITable)
	{{range .Structs}}
	tab.{{.Data 1}} = New{{.Data 1}}()
    tab.Tables["{{.FileName}}.json"] = tab.{{.Data 1}}
	{{end}}
}
