// Generated by g.f.com/flora/weiss/tabtoy
// Version: 0.0.0
// DO NOT EDIT!!
using System.Collections.Generic;
using tabtoy;

namespace Table
{

	public static partial class EnumAlias {
		
		public static string Name(this FoodType e)
        {
            switch ((int)e)
            {
					
				case 0:
					return "";
					
				case 1:
					return "攻击";
					
				case 3:
					return "防御";
				
            }
			return "";
		}
		
	}


	
	// Defined in table: Globals
	public enum FoodType
	{
		
		
		None = 0, // 
		
		
		Food1 = 1, // 攻击
		
		
		Food2 = 3, // 防御
	
	}
	
	

	// Defined in table: GlobalTable
	
	public partial class GlobalTable
	{
	
	
		#region Index code
	 	
		public string GetBuildID(){
			return "c28b7b0f3d6d2641b497250ddaa3b9fa";
		}
	
		#endregion
		#region Deserialize code
		
		static DeserializeHandler<GlobalTable> _GlobalTableDeserializeHandler;
		public static DeserializeHandler<GlobalTable> GlobalTableDeserializeHandler
		{
			get
			{
				if (_GlobalTableDeserializeHandler == null )
				{
					_GlobalTableDeserializeHandler = new DeserializeHandler<GlobalTable>(DeserializeGlobalTable);
				}

				return _GlobalTableDeserializeHandler;
			}
		}
		public static void DeserializeGlobalTable( GlobalTable ins, DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                }
             } 

			
		}
		static DeserializeHandler<Vec2> _Vec2DeserializeHandler;
		public static DeserializeHandler<Vec2> Vec2DeserializeHandler
		{
			get
			{
				if (_Vec2DeserializeHandler == null )
				{
					_Vec2DeserializeHandler = new DeserializeHandler<Vec2>(DeserializeVec2);
				}

				return _Vec2DeserializeHandler;
			}
		}
		public static void DeserializeVec2( Vec2 ins, DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0x50000:
                	{
						ins.X = reader.ReadFloat();
                	}
                	break; 
                	case 0x50001:
                	{
						ins.Y = reader.ReadFloat();
                	}
                	break; 
                }
             } 

			
		}
		static DeserializeHandler<Vec3> _Vec3DeserializeHandler;
		public static DeserializeHandler<Vec3> Vec3DeserializeHandler
		{
			get
			{
				if (_Vec3DeserializeHandler == null )
				{
					_Vec3DeserializeHandler = new DeserializeHandler<Vec3>(DeserializeVec3);
				}

				return _Vec3DeserializeHandler;
			}
		}
		public static void DeserializeVec3( Vec3 ins, DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0x50000:
                	{
						ins.X = reader.ReadFloat();
                	}
                	break; 
                	case 0x50001:
                	{
						ins.Y = reader.ReadFloat();
                	}
                	break; 
                	case 0x50002:
                	{
						ins.Z = reader.ReadFloat();
                	}
                	break; 
                }
             } 

			
		}
		#endregion
		#region Clear Code
		public void Clear( )
		{	
			
		}
		#endregion
	

	} 

	// Defined in table: Globals
	
	public partial class Vec2
	{
		
		
		public float X = 0f; // 
		
		
		public float Y = 0f; // 
	
	

	} 

	// Defined in table: Globals
	
	public partial class Vec3
	{
		
		
		public float X = 0f; // 
		
		
		public float Y = 0f; // 
		
		
		public float Z = 0f; // 
	
	

	} 

}
